### ISSUE TITLE
bug: Unexpected Error: Need to implement 'codeFor_activateApp()': undefined

### ISSUE THREAD

**Issue by zinthose** [appium/appium-inspector#1003]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The inspector raises an error when attempting to activate an app via the command...`Device/App/Activate App`

When executed, the emulated Android device will open / activate the target app but the Inspector crashes with an error showing the stack trace shown below in "_Further Information_"

_This error only occurs when the Inspector is recording. When the Recorder is not active the command works as espected._

### Expected Behavior

While Recorder is running, execute the Command `Device/App/Activate App` and have the app activated and code added to the Recorder pane.

### Operating System

Windows

### Appium Inspector Version

2023.7.1

### Appium Version

2.0.1

### Further Information

```
Full error trace:
Error: Need to implement 'codeFor_activateApp()': undefined
    at o.getCodeString (file:///C:/Users/nurse/AppData/Local/Programs/Appium%20Inspector/resources/app.asar/dist/renderer.e31bb0bc.js:16:1230)
    at m (file:///C:/Users/nurse/AppData/Local/Programs/Appium%20Inspector/resources/app.asar/dist/renderer.e31bb0bc.js:144:596)
    at c (file:///C:/Users/nurse/AppData/Local/Programs/Appium%20Inspector/resources/app.asar/dist/renderer.e31bb0bc.js:144:666)
    at renderWithHooks (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:16305:18)
    at updateFunctionComponent (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19588:20)
    at beginWork (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21601:16)
    at beginWork$1 (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27426:14)
    at performUnitOfWork (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26560:12)
    at workLoopSync (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26466:5)
    at renderRootSync (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26434:7)
    at recoverFromConcurrentError (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26096:20)
    at flushSyncCallbacks (C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12042:22)
    at C:\Users\nurse\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:25651:13
```

**Comment by eglitise** [comment]
Yes, the recorder methods are likely to be outdated. There are multiple related issues about this (#156, #60, #226, #506).

**Comment by skysolf** [comment]
I have the same bug

**Comment by eglitise** [comment]
All current recorder scripts have now been updated, including support for the `activateApp` method. The changes will be included in the next release.
