### ISSUE TITLE
bug: Unexpected Error: Invariant failed: A state mutation was detected between dispatches

### ISSUE THREAD

**Issue by dcboycm** [appium/appium-inspector#1017]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When editing a newly added gesture I received an error - Unexpected Error: Invariant failed: A state mutation was detected between dispatches, in the path 'inspector.savedGestures.2.actions.0.ticks.1.duration'. This may cause incorrect behavior. (https://redux.js.org/style-guide/style-guide#do-not-mutate-state)

### Expected Behavior

It should allow me to edit the gesture after creating it.

### Operating System

Mac

### Appium Inspector Version

2.0.0-rc.5

### Appium Version

2.0.0-rc.5

### Further Information

Error: Invariant failed: A state mutation was detected between dispatches, in the path 'inspector.savedGestures.2.actions.0.ticks.1.duration'.  This may cause incorrect behavior. (https://redux.js.org/style-guide/style-guide#do-not-mutate-state)
    at invariant (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:325:11)
    at /Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:442:17
    at Object.measureTime (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:223:24)
    at /Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:438:26
    at boundActionCreators.<computed> (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-redux/lib/utils/bindActionCreators.js:13:47)
    at O.onDraw (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:152:3209)
    at O.componentDidUpdate (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:152:2165)
    at commitLayoutEffectOnFiber (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23338:28)
    at commitLayoutMountEffects_complete (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24674:7)
    at commitLayoutEffects_begin (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24656:11)
    at commitLayoutEffects (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24612:3)
    at commitRootImpl (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26823:5)
    at commitRoot (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
    at performSyncWorkOnRoot (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26117:3)
    at flushSyncCallbacks (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12042:22)

**Comment by eglitise** [comment]
You haven't specified the Appium Inspector version (you have listed the Appium version instead), but I assume you are using 2023.6.2 or earlier. Please try again with 2023.7.1, it includes various stability fixes for the gesture editor.

**Comment by eglitise** [comment]
Closing due to no response
