### ISSUE TITLE
bug: <Appium Inspector Create Gesture Error>

### ISSUE THREAD

**Issue by leunghpww** [appium/appium-inspector#1543]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I want to create or edit a gesture in appium inspector, the app pops out error message.

### Expected Behavior

Gesture creating window should be shown.

### Operating System

Windows

### Appium Inspector Version

2024.6.1

### Appium Version

2.6.0

### Further Information

Unexpected Error: Cannot destructure property 'width' of '_' as it is undefined.
Please report this issue at: https://github.com/appium/appium-inspector/issues/new/choose
Full error trace:
TypeError: Cannot destructure property 'width' of '_' as it is undefined.
    at Y (file:///C:/Users/01612597/AppData/Local/Programs/Appium%20Inspector/resources/app.asar/dist/src.6ebfba02.js:138:2038)
    at file:///C:/Users/01612597/AppData/Local/Programs/Appium%20Inspector/resources/app.asar/dist/src.6ebfba02.js:138:1499
    at commitHookEffectListMount (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24970:11)
    at commitPassiveMountEffects_complete (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24917:7)
    at commitPassiveMountEffects (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27078:3)
    at flushPassiveEffects (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27023:14)
    at commitRootImpl (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26974:5)
    at commitRoot (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26721:5)
    at performSyncWorkOnRoot (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26156:3)
    at flushSyncCallbacks (C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12042:22)
    at C:\Users\01612597\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:25690:13

**Comment by eglitise** [comment]
Thanks for the report. Could you please provide the full Appium server log?

**Comment by eglitise** [comment]
I can reproduce the issue if I try to create a gesture while the initial app screenshot has not loaded yet.

**Comment by leunghpww** [comment]
Today, I tried again and found the bug is fixed
