### ISSUE TITLE
Cannot destructure property 'width' of 'O' as it is undefined.

### ISSUE THREAD

**Issue by vnair1986** [appium/appium-inspector#1582]
TypeError: Cannot destructure property 'width' of 'O' as it is undefined.
    at z (file:///C:/Users/VipinNair/AppData/Local/Programs/Appium%20Inspector/resources/app.asar/dist/renderer.e31bb0bc.js:122:2318)
    at file:///C:/Users/VipinNair/AppData/Local/Programs/Appium%20Inspector/resources/app.asar/dist/renderer.e31bb0bc.js:122:1835
    at commitHookEffectListMount (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24931:11)
    at commitPassiveMountEffects_complete (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24878:7)
    at commitPassiveMountEffects (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27039:3)
    at flushPassiveEffects (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26984:14)
    at commitRootImpl (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26935:5)
    at commitRoot (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26682:5)
    at performSyncWorkOnRoot (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26117:3)
    at flushSyncCallbacks (C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12042:22)
    at C:\Users\VipinNair\AppData\Local\Programs\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:25651:13
    
    
    
    
<img width="803" alt="image" src="https://github.com/user-attachments/assets/9a7f748c-6f52-43d8-b1bc-bc54d6755535">

**Comment by eglitise** [comment]
Please provide more details:
* your Appium Inspector version
* your full Appium server log
* what action in the Inspector caused the error

**Comment by sachigoyal** [comment]
Hello @vnair1986 
Try one of these
1. Try providing the default value in the function arg example 
`function MyComponent({ size = {} }) `
Here the size ensures that if size is undefined it will default to an empty object. That way destructing wont cause error.
2. You can check before destructing  that,  taking the above example the size is defined or not.
Thankyou

**Comment by eglitise** [comment]
Closing due to no response from reporter
