### ISSUE TITLE
Clicking on Search for element yields an error message

### ISSUE THREAD

**Issue by wjq1** [appium/appium-inspector#1743]
Unhandled Exception
An unexpected error occurred with message: Cannot read property 'toLowerCase' of undefined.
Please kindly open up a bug report at https://github.com/appium/appium-inspector/issues/new.
TypeError: Cannot read property 'toLowerCase' of undefined
    at g (file:///D:/app%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95%E5%B7%A5%E5%85%B7/Appium-Inspector-windows-2023.5.2/resources/app.asar/dist/renderer.e31bb0bc.js:136:1197)
    at v.render (file:///D:/app%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95%E5%B7%A5%E5%85%B7/Appium-Inspector-windows-2023.5.2/resources/app.asar/dist/renderer.e31bb0bc.js:136:2082)
    at finishClassComponent (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17485:31)
    at updateClassComponent (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17435:24)
    at beginWork (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:3994:16)
    at invokeGuardedCallback (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4056:31)
    at beginWork$1 (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23964:7)
    at performUnitOfWork (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22779:12)
    at workLoopSync (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22707:5)
    at renderRootSync (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22670:7)
    at performSyncWorkOnRoot (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22293:18)
    at D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11327:26
    at unstable_runWithPriority (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:468:12)
    at runWithPriority$1 (D:\app自动化测试工具\Appium-Inspector-windows-2023.5.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11276:10)

**Comment by wjq1** [comment]
ok
