### ISSUE TITLE
[v2022.3.2 on MacOS] JS error when opening an app

### ISSUE THREAD

**Issue by yavgel** [appium/appium-inspector#339]
![image](https://user-images.githubusercontent.com/8123409/158585523-6a1f3c94-b099-4762-87b8-35022a865fa4.png)

--------

![image](https://user-images.githubusercontent.com/8123409/158589335-fc37c353-291a-4dff-bde6-815549fc1717.png)

**Comment by zaphodikus** [comment]
I last used Appium 3 years ago (MacOS Big Sur) . Installed Appium Server yesterday and installed Inspector today, bang, blocked.

Have installed version 2022.2.1 instead, and that appears to not have issue. :-)

**Comment by AbhinavShingate** [comment]
<img width="265" alt="Screenshot 2022-03-16 at 15 50 22" src="https://user-images.githubusercontent.com/32419852/158618149-2a93e991-9a05-4ec3-b3c0-e6d4c7e01176.png">
same issue for me

**Comment by RSUIAutomation** [comment]
Here is full text of the error I am seeing when just trying to install fresh:

```Uncaught Exception:
Error: Could not get code signature for running application
at s (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:20:717)
at Object.parcelRequire.oCSp../config (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:28:644)
at f (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:1:468)
at p (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:1:544)
at Object.parcelRequire.iJo8../auto-updater (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:32:120)
at f (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:1:468)
at p (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:1:544)
at Object.parcelRequire.epB2../configs/i18next.config (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:34:151)
at f (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:1:468)
at parcelRequire.EeG0 (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:1:771)
at Object.<anonymous> (/Applications/Appium Inspector.app/Contents/Resources/app.asar/dist/main.js:1:1023)
at Module._compile (internal/modules/cjs/loader.js:1078:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
at __webpack_require__ (electron/js2c/browser_init.js:1:128)
at electron/js2c/browser_init.js:1:1200
at electron/js2c/browser_init.js:1:1267
at 
```

**Comment by RSUIAutomation** [comment]
Rolling back to the feb version resolved this issue.

**Comment by zgordon02** [comment]
The solution was found here: https://github.com/appium/appium-inspector/issues/343

**Comment by jlipps** [comment]
i unpublished the 2022.3.2 release, seems like something changed with code signing in our CI
