### ISSUE TITLE
Appium Inspector is not able to record script

### ISSUE THREAD

**Issue by wwwuxiao1** [appium/appium-inspector#500]
TypeError: n.default[a] is not a constructor
    at m.code (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:140:1227)
    at m.render (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:140:2696)
    at finishClassComponent (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
    at updateClassComponent (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
    at beginWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
    at performUnitOfWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22779:12)
    at workLoopSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
    at renderRootSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
    at performSyncWorkOnRoot (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
    at /Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11327:26
    at unstable_runWithPriority (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276:10)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Which language is active? Which action did you take?

**Comment by AtulKrSharma** [comment]
I'm facing the same issue with Appium Inspector (App Version: 2022.7.1)

**Environment**
1. Appium Desktop
2.  Windows 10
3. Appium Java Client



![image](https://user-images.githubusercontent.com/49794348/201508631-4a638490-a8a0-4c97-8bc4-fe397916f445.png)

**Comment by jlipps** [comment]
Try the latest version, and please answer the unanswered questions above

**Comment by eglitise** [comment]
Closing due to no response
