### ISSUE TITLE
appium error 304

### ISSUE THREAD

**Issue by riginnnn** [appium/appium-inspector#734]
## Environment
- appium desktop：v1.22.3-4
- mac
- xcode：14.2
- Real device ：iOS15.6

## Issues

When I use appium inspector to start, appium will repeatedly repeat the Executing command 'getTimeouts'. It will take 5 minutes or longer for appium inspector to load。This makes me unable to locate the element in the inspector。

![image](https://user-images.githubusercontent.com/127721177/224627103-3ccffc67-c17c-43a5-ae8a-25d0f09c014c.png)

After loading, the appium log will continue to report 304 errors
```
[HTTP] --> GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts
[HTTP] {}
[W3C (bf29d257)] Calling AppiumDriver.getTimeouts() with args: ["bf29d257-b379-491f-908d-1ac6cd6502bc"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bf29d257)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts
[HTTP] {}
[W3C (bf29d257)] Calling AppiumDriver.getTimeouts() with args: ["bf29d257-b379-491f-908d-1ac6cd6502bc"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bf29d257)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts
[HTTP] {}
[W3C (bf29d257)] Calling AppiumDriver.getTimeouts() with args: ["bf29d257-b379-491f-908d-1ac6cd6502bc"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bf29d257)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts
[HTTP] {}
[W3C (bf29d257)] Calling AppiumDriver.getTimeouts() with args: ["bf29d257-b379-491f-908d-1ac6cd6502bc"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bf29d257)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts 304 2 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts
[HTTP] {}
[W3C (bf29d257)] Calling AppiumDriver.getTimeouts() with args: ["bf29d257-b379-491f-908d-1ac6cd6502bc"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bf29d257)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bf29d257-b379-491f-908d-1ac6cd6502bc/timeouts 304 2 ms - -
```

**Comment by jlipps** [comment]
what version of appium are you using?

**Comment by riginnnn** [comment]
> what version of appium are you using?

appium desktop v1.22.3-4

**Comment by riginnnn** [comment]
this is the relevant log
[appium-server-logs.txt](https://github.com/appium/appium-inspector/files/10963513/appium-server-logs.txt)

**Comment by jlipps** [comment]
appium desktop is no longer supported. please use the latest appium inspector from this repo in conjunction with an appium 2 server.

**Comment by riginnnn** [comment]
Appium 2 server has the same problem @jlipps

**Comment by riginnnn** [comment]
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/127721177/225524965-887e9726-ae4e-47bb-aa12-4b040cb49869.png">

**Comment by jlipps** [comment]
please include the full appium 2 server log

**Comment by riginnnn** [comment]
> please include the full appium 2 server log

[appium-server-logs.txt](https://github.com/appium/appium-inspector/files/10997176/appium-server-logs.txt)

**Comment by riginnnn** [comment]
@jlipps

**Comment by jlipps** [comment]
I admit I have no idea why the route would switch to sending a 304 response at some point. I checked our server logic and don't see anything that could be making that happen. at any rate I don't think it's the root cause of the issue you reported. but if you want to keep tracking things down, tell me the exact version of the inspector you're using and run the appium 2 server with `--log-timestamp` so we can check the timings

**Comment by amenamabrouk** [comment]
Hello @jlipps I am running in to the same issue as well. I am currently utilizing the latest version of Appium Inspector, and the command line version of Appium to inspect elements for Android automation.  

Appium version: 1.22.3
Appium inspector version: Appium-Inspector-mac-2023.4.1.dmg

Please advise on how to mitigate this issue. Thank you. 

<img width="1325" alt="Screen Shot 2023-04-19 at 1 18 39 AM" src="https://user-images.githubusercontent.com/47794857/232983627-710edd6e-3203-4c45-bc4f-772bffea2c14.png">

**Comment by adityaanand951** [comment]
INGUR1M0465:~ xxxxx$ appium server --log-timestamp
2023-07-31 12:29:59:783 - [Appium] Welcome to Appium v2.0.1
2023-07-31 12:29:59:784 - [Appium] Non-default server args:
2023-07-31 12:29:59:784 - [Appium] {
2023-07-31 12:29:59:784 - [Appium]   logTimestamp: true
2023-07-31 12:29:59:784 - [Appium] }
2023-07-31 12:29:59:785 - [Appium] Attempting to load driver chromium...
2023-07-31 12:29:59:786 - [debug] [Appium] Requiring driver at /Users/adityann/node_modules/appium-chromium-driver
2023-07-31 12:30:00:568 - [Appium] Attempting to load driver xcuitest...
2023-07-31 12:30:00:569 - [debug] [Appium] Requiring driver at /Users/adityann/node_modules/appium-xcuitest-driver
2023-07-31 12:30:01:292 - [Appium] Appium REST http interface listener started on http://0.0.0.0:4723
2023-07-31 12:30:01:293 - [Appium] You can provide the following URLS in your client code to connect to this server:
2023-07-31 12:30:01:293 - [Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
2023-07-31 12:30:01:293 - [Appium] 	http://10.177.183.77:4723/
2023-07-31 12:30:01:293 - [Appium] 	http://169.254.71.130:4723/
2023-07-31 12:30:01:294 - [Appium] Available drivers:
2023-07-31 12:30:01:294 - [Appium]   - chromium@1.1.20 (automationName 'Chromium')
2023-07-31 12:30:01:294 - [Appium]   - xcuitest@4.32.23 (automationName 'XCUITest')
2023-07-31 12:30:01:294 - [Appium] Available plugins:
2023-07-31 12:30:01:294 - [Appium]   - execute-driver@3.0.15
2023-07-31 12:30:01:294 - [Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
2023-07-31 12:30:09:703 - [HTTP] --> GET /session/7402f93b-365d-4b77-9654-0278c62170be/timeouts
2023-07-31 12:30:09:703 - [HTTP] {}
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:315:15)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:518:15
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:144:13)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:114:3)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:113:7)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
2023-07-31 12:30:09:714 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:09:716 - [HTTP] <-- GET /session/7402f93b-365d-4b77-9654-0278c62170be/timeouts 404 13 ms - 3160
2023-07-31 12:30:09:717 - [HTTP] 
2023-07-31 12:30:12:670 - [HTTP] --> DELETE /session/7402f93b-365d-4b77-9654-0278c62170be
2023-07-31 12:30:12:670 - [HTTP] {}
2023-07-31 12:30:12:673 - [debug] [AppiumDriver@9f47] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2023-07-31 12:30:12:673 - [debug] [AppiumDriver@9f47]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:315:15)
2023-07-31 12:30:12:673 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:518:15
2023-07-31 12:30:12:673 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:12:673 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:144:13)
2023-07-31 12:30:12:674 - [debug] [AppiumDriver@9f47]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:114:3)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
2023-07-31 12:30:12:675 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:113:7)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
2023-07-31 12:30:12:676 - [debug] [AppiumDriver@9f47]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
2023-07-31 12:30:12:677 - [debug] [AppiumDriver@9f47]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
2023-07-31 12:30:12:679 - [HTTP] <-- DELETE /session/7402f93b-365d-4b77-9654-0278c62170be 404 8 ms - 3160
2023-07-31 12:30:12:680 - [HTTP] 
2023-07-31 12:30:12:895 - [HTTP] --> GET /sessions
2023-07-31 12:30:12:895 - [HTTP] {}


I am receiving this I don't understand the scenario Please look into this why I am receiving this.

**Comment by riginnnn** [comment]
I found the cause of the problem, which is that the application is too complex and the presentation of the appium inspector is too slow. If you switch to a simple application, there won't be a 304 error message

**Comment by jlipps** [comment]
Yeah makes sense. It's not the fault of the inspector. It's just appium / your app taking a long time to get the source tree.

**Comment by riginnnn** [comment]
It would be even better if the speed of obtaining the structure tree can be improved.I use appium2.0 or appium1.0, the speed is the same

**Comment by jlipps** [comment]
The speed of obtaining the tree is the responsibility of the driver, in this case the xcuitest driver, so it makes sense that it doesn't matter the version of Appium you use. If you think there's a bug in the driver you can report it. Most likely it's a performance issue in Apple's lower level frameworks that the driver depends on, and there may not be anything the xcuitest driver team can do about it.

**Comment by Julianamendes2784** [comment]
Também tive o mesmo problema e foi preciso rodar o comando: appium-doctor para verificar alguma inconsistência. No meu caso, como eu tinha atualizado a versão do Mac para o Ventura, acabou zuando as minhas variáveis ANDROID_HOME e JAVA_HOME. Refiz as configurações delas, rodei novamente um appium-doctor no terminal e vi que já estavam apontando como resolvidas as variáveis. Então, encerrei o appium doctor. Subi o meu emulador via terminal e desliguei ele. Depois, abri um novo terminal e rodei o comando abaixo para resetar o emulador: emulator NomeDoEmulador -wipe-data Feito isso, Startei o novamente o emulador e em seguida startei a sessão do appium inspector e deu sucesso.

**Comment by viniborg** [comment]
I'm facing the same issue. When running tests using Appium and Java for iOS platform, targeting physical device or emulator, at a certain point the server starts returning 304, as shown in the example below:

<img width="1053" alt="Captura de Tela 2024-04-02 às 11 59 38" src="https://github.com/appium/appium-inspector/assets/83841507/0258232d-8419-4f71-84eb-5c6f6712249b">
[appium.txt](https://github.com/appium/appium-inspector/files/14839016/appium.txt)

I'm using Xcuitest version 4.21.6, with Appium 2.4.1.

Can you help? @jlipps

**Comment by eglitise** [comment]
@viniborg your log is very confusing because there are many different Appium sessions and shell commands. From what I can see, one reason for the problems could be that you ran `rm -rf /Users/c91684a/.appium/node_modules/appium-xcuitest-driver` without first uninstalling it. This is a bad idea because XCUITest driver has many other dependencies, and just deleting its folder does not remove these dependencies. So you can end up with dependencies that do not work with your driver version (e.g. I see WebDriverAgent `8.4.0`, which is a lot more recent than XCUITest driver `4.21.6`)
I would advise to delete the whole driver directory by running `rm -rf /Users/c91684a/.appium` and then installing the drivers anew.
Also, 304s are entirely normal and expected during an Inspector session. It looks like you may have multiple sessions running on the same server.
