### ISSUE TITLE
I have the issue in last version of the appium 

### ISSUE THREAD

**Issue by Ahmadawad1254** [appium/appium-inspector#853]
## Appium or Appium Inspector?

You are reporting an issue at the Appium Inspector repository. Appium Inspector is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Inspector but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Inspector version _<insert version here>_.
- I am on (pick one):
  
    - [1 ] Windows

**Comment by eglitise** [comment]
Please describe your issue, and specify more details about your environment.

**Comment by eglitise** [comment]
Closing due to no response

**Comment by Ahmadawad1254** [comment]
Sorry to be late, The application is crash and appear exception same as this :

Once opening the app , and appear loading icon is too much ??

________________________________

**Comment by Ahmadawad1254** [comment]
Hello Dears,

My environment is a last version of the window 10 and last version of the Appium inspector.

When I tried to open a last version of the Appium inspector on my Mac (window 10 ) it did not work appear exception message. Once click on the new icon loading this message will appear.
I hope a screen shoot is clear as attachment.

[Appium
File View Help
Unhandled Exception
An unexpected error occurred with message: Couldn't find session with uuid 63036141-01ac-47e6-aa34-1319f25d18cb.
Please kindly open up a bug report at https://github.com/appium/appium-inspector/issues/new.
Error: Couldn't find session with uuid 63036141-01ac-47e6-aa34-1319f25d18cb
at
p.sessionFromUUID (file:///C:/Program%20Files/Appium%20Inspector/resources/app.asar/dist/renderer.e31bb0bc.js:108:1884)
at p.render (file:///C:/Program%20Files/Appium%20Inspector/resources/app.asar/dist/renderer.e31bb0bc.js:108:2997)
at finishClassComponent (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17485:31) at updateClassComponent (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17435:24)
at beginWork (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19073:16)
at HTMLUnknown Element.callCallback (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:3945:14) at Object.invokeGuardedCallbackDev (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:3994:16)
at invokeGuardedCallback (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4056:31)
at beginWork$1 (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23964:7)
at performUnitOfWork (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22779:12) at workLoop Sync (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22707:5) at renderRootSync (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22670:7)
at performSyncWorkOnRoot (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22293:18) at C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11327:26
at unstable_runWithPriority (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:468:12) at runWithPriority$1 (C:\Program Files\Appium Inspector\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11276:10)]
________________________________

**Comment by jlipps** [comment]
Can you also attach a screenshot?

**Comment by Ahmadawad1254** [comment]
Of course, here above ok.

________________________________

**Comment by jlipps** [comment]
I don't see a screenshot. You may need to come to the issue URL on GitHub and upload it.

**Comment by Ahmadawad1254** [comment]
Ok.
________________________________

**Comment by eglitise** [comment]
Hmm, this looks to be related to the saved capability sets. Does this error appear on its own right after the splash screen, or are you doing some actions that cause it?
Also, by latest version, do you mean version 2023.5.2, or 2023.5.1? There was a possible race condition in 2023.5.1 that should be fixed in 2023.5.2. Please try both versions in either case.

**Comment by jlipps** [comment]
Could it be that a data structure changed and so the user might need to clear out the local data and start over with saved sets?

**Comment by eglitise** [comment]
It's plausible, but I don't think there were any changes to this structure in the last year...?
Also, is there even a way to delete the local data? Guessing it's stored somewhere in the save location for `electron-settings`...

**Comment by Ahmadawad1254** [comment]
The Appium inspector version is :  

![image](https://github.com/appium/appium-inspector/assets/119678331/f812c531-c6c3-47ea-a174-b2329269f8f9)

**Comment by Ahmadawad1254** [comment]
Well, I will try the same scenario on another version.

**Comment by eglitise** [comment]
Yes, please try with 2023.5.2.

**Comment by eglitise** [comment]
Closing due to no response
